language: php

sudo: false

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

install:
    - travis_retry composer install --no-interaction

script:
    - ./vendor/bin/phpunit --coverage-text
    - ./vendor/bin/psalm --find-dead-code
    - ./vendor/bin/phpcs -p --standard=PSR2 --runtime-set ignore_errors_on_exit 1 --runtime-set ignore_warnings_on_exit 1 src Tests

cache:
    directories:
        - ./vendor/
        - $HOME/.cache/composer
